# Generated by Django 5.1.7 on 2025-07-13 22:54

import django.db.models.deletion
import django.utils.timezone
import prestamos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateField(default=prestamos.models.default_fecha_devolucion)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto')], default='activo', max_length=20)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.ejemplar')),
            ],
        ),
    ]
